openapi:
  title: portfolio API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.
  enable: true

# postgres:
#   host: 0.0.0.0
#   database: postgres
#   port: "5432"
#   username: username
#   password: password
#   ssl: disable
sqlite:
  create_if_missing: true
  database_path: database.db
redis:
  port: 6379
  host:  0.0.0.0
server:
  port: 8080
  host: 0.0.0.0

storage:
  provider: local  # opções: local, s3, firebase
  local:
    folder: './uploads'
  s3:
    bucket: 'meu-bucket'
    region: 'us-east-1'
    accessKey: 'sua_access_key'
    secretKey: 'seu_secret_key'
  firebase:
    projectId: 'my-project'
    apiKey: 'my_api'

env:
  mode: debug