name: portfolio
description: fdf.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  # redis: ^4.0.0
  sqlite3: ^2.7.5
  # postgres: ^3.5.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.2
  vaden: ^0.0.8

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.0.8